# spring
spring:
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://host:port/database?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: 
      password: 
# log
logging:
  level:
    project009.com.project.war: debug