# spring
spring:
  # profiles
  profiles:
    active: local
# framework
framework:
  # swagger
  swagger:
    base-package: project009.com.project.war.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    project009.com.project.war: info
# mybatis plus
mybatis-plus:
  type-aliases-package: project009.com.project.war.entity,project009.com.project.war.model.*
  mapper-locations: classpath:mappers/*Mapper.xml
